# Generated by Django 6.0 on 2026-01-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendscore',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
