# Generated by Django 6.0 on 2026-01-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_alter_sendscore_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendscore',
            name='score',
            field=models.FloatField(),
        ),
    ]
