# Generated by Django 6.0 on 2026-01-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_alter_sendscore_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendscore',
            old_name='name',
            new_name='username',
        ),
    ]
